name: Deploy and Test Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: kind create cluster --wait 5m

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Check cluster status
        run: kubectl cluster-info

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy application with Helm
        run: |
          helm upgrade --install flask-app ./helm --wait

      - name: Wait for application to be ready
        run: |
          kubectl rollout status deployment/flask-app

  test-application:
    runs-on: ubuntu-latest
    needs: setup-cluster

    steps:
      - name: Set kubectl context
        run: kubectl config use-context kind-kind || exit 1

      - name: Check Ingress
        run: |
          kubectl get ingress
          kubectl describe ingress flask-app-ingress

      - name: Test application endpoints
        run: |
          curl http://rickandmorty.local/healthcheck
          curl http://rickandmorty.local/characters

  cleanup:
    runs-on: ubuntu-latest
    needs: [setup-cluster, test-application]

    steps:
      - name: Delete Kind cluster
        run: kind delete cluster
