name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: kind create cluster --wait 5m

      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic
          
      - name: Deploy application to Kubernetes
        run: |
          kubectl apply -f yamls/

  test-application:
    runs-on: ubuntu-latest
    needs: create-cluster
    steps:
      - name: Test application endpoints
        run: |
          curl http://rickandmorty.local/healthcheck
          curl http://rickandmorty.local/characters
